language: cpp
os:
 - linux
sudo: true
notifications:
 email:
  on_success: change # [always|never|change] # default: change
  on_failure: always # [always|never|change] # default: always

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.9
    - g++-5
    
env:
#disabled because the linker crashes
# - CPP=g++-5   PEDANTIC=OFF NO_EXCEPTIONS=OFF NO_RTTI=OFF TEST_INCLUDES=OFF WARNING_IS_ERROR=ON BUILD_TYPE=Release CONAN="-s compiler.version=5.4 -s build_type=Release"
# - CPP=g++-5   PEDANTIC=OFF NO_EXCEPTIONS=OFF NO_RTTI=OFF TEST_INCLUDES=OFF WARNING_IS_ERROR=ON BUILD_TYPE=Debug   CONAN="-s compiler.version=5.4 -s build_type=Debug"
 - CPP=g++-4.9 PEDANTIC=OFF NO_EXCEPTIONS=OFF NO_RTTI=OFF TEST_INCLUDES=OFF WARNING_IS_ERROR=ON BUILD_TYPE=Release CONAN="-s compiler.version=4.9 -s build_type=Release"
 - CPP=g++-4.9 PEDANTIC=OFF NO_EXCEPTIONS=OFF NO_RTTI=OFF TEST_INCLUDES=OFF WARNING_IS_ERROR=ON BUILD_TYPE=Debug   CONAN="-s compiler.version=4.9 -s build_type=Debug"

before_install:
 - git submodule update --init --recursive

install:
 - wget https://github.com/conan-io/conan/releases/download/0.20.2/conan-ubuntu-64_0_20_2.deb -O conan.deb || exit 1
 - sudo dpkg -i conan.deb || exit 1
 - rm conan.deb || exit 1
 - conan --version

 - wget https://s3.amazonaws.com/biibinaries/thirdparty/cmake-3.0.2-Linux-64.tar.gz
 - tar -xzf cmake-3.0.2-Linux-64.tar.gz
 - sudo cp -fR cmake-3.0.2-Linux-64/* /usr
 - rm -rf cmake-3.0.2-Linux-64
 - rm cmake-3.0.2-Linux-64.tar.gz

script:
 - mkdir build-silicium
 - pushd build-silicium
 - CXX=$CPP conan install -s compiler=gcc $CONAN .. || exit 1
 - CXX=$CPP cmake .. -DSILICIUM_TEST_INCLUDES=$TEST_INCLUDES -DSILICIUM_PEDANTIC=$PEDANTIC -DSILICIUM_NO_EXCEPTIONS=$NO_EXCEPTIONS -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DSILICIUM_NO_RTTI=$NO_RTTI -DSILICIUM_WARNING_IS_ERROR=$WARNING_IS_ERROR || exit 1
 - cmake --build . -- -j2 || exit 1
 - pushd bin
 - if [ $NO_RTTI != "ON" ]; then
     ./unit_test || exit 1;
   fi
