language: cpp
os:
 - linux
notifications:
 email:
  on_success: change # [always|never|change] # default: change
  on_failure: always # [always|never|change] # default: always

compiler:
 - gcc

env:
 - BOOST=libboost1.55-all-dev TEST_INCLUDES=ON
 - BOOST=libboost1.54-all-dev TEST_INCLUDES=OFF

before_install:
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo add-apt-repository -y ppa:boost-latest/ppa
 - sudo apt-get update -qq
 - sudo apt-get install -qq $BOOST cmake liburiparser-dev
 - sudo apt-get install -qq $GCCVER
 - git submodule update --init --recursive

script:
 - mkdir build
 - cd build
 - cmake .. -DSILICIUM_USE_WEBSOCKETPP=OFF -DSILICIUM_TEST_INCLUDES=$TEST_INCLUDES
 - cmake --build .
 - ./test/unit_test
