language: cpp
os:
 - linux
sudo: false
notifications:
 email:
  on_success: change # [always|never|change] # default: change
  on_failure: always # [always|never|change] # default: always

addons:
  apt:
    sources:
    - boost-latest
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
    - g++-4.9
    - g++-4.8
    - g++-4.7
    - g++-4.6
    
env:
#TODO: make Boost.Chrono optional because it was introduced in Boost 1.47 
# - CXX=g++-5   BOOST=libboost1.46-all-dev WEBSOCKETPP=OFF PEDANTIC=ON  NO_EXCEPTIONS=OFF NO_RTTI=OFF TEST_INCLUDES=OFF BUILD_TYPE=Release

#TODO: make boost/type_traits/is_nothrow_move_assignable.hpp optional
# - CXX=g++-5   BOOST=libboost1.48-all-dev WEBSOCKETPP=OFF PEDANTIC=ON  NO_EXCEPTIONS=OFF NO_RTTI=OFF TEST_INCLUDES=OFF BUILD_TYPE=Release

 - CPP=g++-5   BOOST=libboost1.55-all-dev WEBSOCKETPP=OFF PEDANTIC=ON  NO_EXCEPTIONS=ON  NO_RTTI=OFF TEST_INCLUDES=OFF BUILD_TYPE=Release
 - CPP=g++-5   BOOST=libboost1.55-all-dev WEBSOCKETPP=OFF PEDANTIC=ON  NO_EXCEPTIONS=OFF NO_RTTI=ON  TEST_INCLUDES=OFF BUILD_TYPE=Release
 - CPP=g++-5   BOOST=libboost1.55-all-dev WEBSOCKETPP=OFF PEDANTIC=ON  NO_EXCEPTIONS=OFF NO_RTTI=OFF TEST_INCLUDES=ON  BUILD_TYPE=Release
 - CPP=g++-5   BOOST=libboost1.54-all-dev WEBSOCKETPP=OFF PEDANTIC=ON  NO_EXCEPTIONS=OFF NO_RTTI=OFF TEST_INCLUDES=OFF BUILD_TYPE=Debug
 - CPP=g++-4.9 BOOST=libboost1.55-all-dev WEBSOCKETPP=OFF PEDANTIC=OFF NO_EXCEPTIONS=OFF NO_RTTI=OFF TEST_INCLUDES=OFF BUILD_TYPE=Release
 - CPP=g++-4.9 BOOST=libboost1.54-all-dev WEBSOCKETPP=OFF PEDANTIC=OFF NO_EXCEPTIONS=OFF NO_RTTI=OFF TEST_INCLUDES=OFF BUILD_TYPE=Debug
 - CPP=g++-4.8 BOOST=libboost1.55-all-dev WEBSOCKETPP=OFF PEDANTIC=OFF NO_EXCEPTIONS=OFF NO_RTTI=OFF TEST_INCLUDES=OFF BUILD_TYPE=Release
 - CPP=g++-4.8 BOOST=libboost1.54-all-dev WEBSOCKETPP=OFF PEDANTIC=OFF NO_EXCEPTIONS=OFF NO_RTTI=OFF TEST_INCLUDES=OFF BUILD_TYPE=Debug
 - CPP=g++-4.7 BOOST=libboost1.55-all-dev WEBSOCKETPP=OFF PEDANTIC=OFF NO_EXCEPTIONS=OFF NO_RTTI=OFF TEST_INCLUDES=OFF BUILD_TYPE=Debug

#TODO: support GCC 4.7 + ancient Boost
 - CPP=g++-4.7 BOOST=libboost1.54-all-dev WEBSOCKETPP=OFF PEDANTIC=OFF NO_EXCEPTIONS=OFF NO_RTTI=OFF TEST_INCLUDES=OFF BUILD_TYPE=Release
 - CPP=g++-4.6 BOOST=libboost1.55-all-dev WEBSOCKETPP=OFF PEDANTIC=OFF NO_EXCEPTIONS=OFF NO_RTTI=OFF TEST_INCLUDES=OFF BUILD_TYPE=Debug
 - CPP=g++-4.6 BOOST=libboost1.54-all-dev WEBSOCKETPP=OFF PEDANTIC=OFF NO_EXCEPTIONS=OFF NO_RTTI=OFF TEST_INCLUDES=OFF BUILD_TYPE=Release

before_install:
 - git submodule update --init --recursive

script:
 - mkdir build
 - cd build
 - CXX=$CPP cmake .. -DSILICIUM_USE_WEBSOCKETPP=$WEBSOCKETPP -DSILICIUM_TEST_INCLUDES=$TEST_INCLUDES -DSILICIUM_PEDANTIC=$PEDANTIC -DSILICIUM_NO_EXCEPTIONS=$NO_EXCEPTIONS -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DSILICIUM_TESTS_RUNNING_ON_TRAVIS_CI=ON -DSILICIUM_NO_RTTI=$NO_RTTI || exit 1
 - cmake --build . -- -j2 || exit 1
 - cd test
 - if [ $NO_RTTI != "ON" ]; then
     ./unit_test || exit 1
     valgrind --leak-check=full --error-exitcode=1 ./unit_test || exit 1;
   fi
 - cd ../system_test
 - if [ $NO_RTTI != "ON" ] && [ $NO_EXCEPTIONS != "ON" ]; then
     ./system_test || exit 1
     valgrind --leak-check=full --error-exitcode=1 ./system_test || exit 1;
   fi
