language: cpp
os:
 - linux
notifications:
 email:
  on_success: change # [always|never|change] # default: change
  on_failure: always # [always|never|change] # default: always

compiler:
 - clang
 - gcc

env:
 - BOOST=libboost1.55-all-dev
 - BOOST=libboost1.54-all-dev
 - BOOST=libboost1.53-all-dev

before_install:
 - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
 - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo add-apt-repository -y ppa:boost-latest/ppa; fi
 - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update -qq; fi
 - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install -qq $BOOST cmake liburiparser-dev; fi
 - if [ "$TRAVIS_OS_NAME" = "linux" ] && [ $GCCVER != "" ]; then sudo apt-get install -qq $GCCVER; fi
 - git submodule update --init --recursive

script:
 - mkdir build
 - cd build
 - cmake .. -DSILICIUM_USE_WEBSOCKETPP=OFF
 - cmake --build .
 - ./test/unit_test
