language: cpp
os:
 - linux
notifications:
 email:
  on_success: change # [always|never|change] # default: change
  on_failure: always # [always|never|change] # default: always

compiler:
 - gcc

env:
#TODO: make Boost.Chrono optional because it was introduced in Boost 1.47 
# - GCC=g++-5   BOOST=libboost1.46-all-dev WEBSOCKETPP=OFF PEDANTIC=ON  NO_EXCEPTIONS=OFF NO_RTTI=OFF TEST_INCLUDES=OFF BUILD_TYPE=Release

#TODO: make boost/type_traits/is_nothrow_move_assignable.hpp optional
# - GCC=g++-5   BOOST=libboost1.48-all-dev WEBSOCKETPP=OFF PEDANTIC=ON  NO_EXCEPTIONS=OFF NO_RTTI=OFF TEST_INCLUDES=OFF BUILD_TYPE=Release

 - GCC=g++-5   BOOST=libboost1.55-all-dev WEBSOCKETPP=OFF PEDANTIC=ON  NO_EXCEPTIONS=ON  NO_RTTI=OFF TEST_INCLUDES=OFF BUILD_TYPE=Release
 - GCC=g++-5   BOOST=libboost1.55-all-dev WEBSOCKETPP=OFF PEDANTIC=ON  NO_EXCEPTIONS=OFF NO_RTTI=ON  TEST_INCLUDES=OFF BUILD_TYPE=Release
 - GCC=g++-5   BOOST=libboost1.55-all-dev WEBSOCKETPP=OFF PEDANTIC=ON  NO_EXCEPTIONS=OFF NO_RTTI=OFF TEST_INCLUDES=ON  BUILD_TYPE=Release
 - GCC=g++-5   BOOST=libboost1.54-all-dev WEBSOCKETPP=OFF PEDANTIC=ON  NO_EXCEPTIONS=OFF NO_RTTI=OFF TEST_INCLUDES=OFF BUILD_TYPE=Debug
 - GCC=g++-4.9 BOOST=libboost1.55-all-dev WEBSOCKETPP=OFF PEDANTIC=OFF NO_EXCEPTIONS=OFF NO_RTTI=OFF TEST_INCLUDES=OFF BUILD_TYPE=Release
 - GCC=g++-4.9 BOOST=libboost1.54-all-dev WEBSOCKETPP=OFF PEDANTIC=OFF NO_EXCEPTIONS=OFF NO_RTTI=OFF TEST_INCLUDES=OFF BUILD_TYPE=Debug
 - GCC=g++-4.8 BOOST=libboost1.55-all-dev WEBSOCKETPP=OFF PEDANTIC=OFF NO_EXCEPTIONS=OFF NO_RTTI=OFF TEST_INCLUDES=OFF BUILD_TYPE=Release
 - GCC=g++-4.8 BOOST=libboost1.54-all-dev WEBSOCKETPP=OFF PEDANTIC=OFF NO_EXCEPTIONS=OFF NO_RTTI=OFF TEST_INCLUDES=OFF BUILD_TYPE=Debug
 - GCC=g++-4.7 BOOST=libboost1.55-all-dev WEBSOCKETPP=OFF PEDANTIC=OFF NO_EXCEPTIONS=OFF NO_RTTI=OFF TEST_INCLUDES=OFF BUILD_TYPE=Debug

#TODO: support GCC 4.7 + ancient Boost
# - GCC=g++-4.7 BOOST=libboost1.54-all-dev WEBSOCKETPP=OFF PEDANTIC=OFF NO_EXCEPTIONS=OFF NO_RTTI=OFF TEST_INCLUDES=OFF BUILD_TYPE=Release
 - GCC=g++-4.6 BOOST=libboost1.55-all-dev WEBSOCKETPP=OFF PEDANTIC=OFF NO_EXCEPTIONS=OFF NO_RTTI=OFF TEST_INCLUDES=OFF BUILD_TYPE=Debug
 - GCC=g++-4.6 BOOST=libboost1.54-all-dev WEBSOCKETPP=OFF PEDANTIC=OFF NO_EXCEPTIONS=OFF NO_RTTI=OFF TEST_INCLUDES=OFF BUILD_TYPE=Release

before_install:
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo add-apt-repository -y ppa:boost-latest/ppa
 - sudo apt-get update -qq
 - sudo apt-get install -qq cmake liburiparser-dev valgrind $GCC $BOOST
 - export CXX=$GCC
 - git submodule update --init --recursive

script:
 - mkdir build
 - cd build
 - cmake .. -DSILICIUM_USE_WEBSOCKETPP=$WEBSOCKETPP -DSILICIUM_TEST_INCLUDES=$TEST_INCLUDES -DSILICIUM_PEDANTIC=$PEDANTIC -DSILICIUM_NO_EXCEPTIONS=$NO_EXCEPTIONS -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DSILICIUM_TESTS_RUNNING_ON_TRAVIS_CI=ON -DSILICIUM_NO_RTTI=$NO_RTTI
 - cmake --build . -- -j2
 - cd test
 - if [ $NO_RTTI != "ON" ]; then valgrind --leak-check=full --error-exitcode=1 ./unit_test; fi
 - cd ../system_test
 - if [ $NO_RTTI != "ON" ] && [ $NO_EXCEPTIONS != "ON" ]; then valgrind --leak-check=full --error-exitcode=1 ./system_test; fi
