language: cpp
os:
 - linux
notifications:
 email:
  on_success: change # [always|never|change] # default: change
  on_failure: always # [always|never|change] # default: always

compiler:
 - gcc

env:
 - GCC=g++-5   BOOST=libboost1.55-all-dev WEBSOCKETPP=OFF PEDANTIC=OFF NO_EXCEPTIONS=OFF BUILD_TYPE=Release
 - GCC=g++-5   BOOST=libboost1.54-all-dev WEBSOCKETPP=OFF PEDANTIC=OFF NO_EXCEPTIONS=OFF BUILD_TYPE=Debug
 - GCC=g++-4.8 BOOST=libboost1.55-all-dev WEBSOCKETPP=OFF PEDANTIC=OFF NO_EXCEPTIONS=OFF BUILD_TYPE=Release
 - GCC=g++-4.8 BOOST=libboost1.54-all-dev WEBSOCKETPP=OFF PEDANTIC=OFF NO_EXCEPTIONS=OFF BUILD_TYPE=Debug
 - GCC=g++-4.7 BOOST=libboost1.55-all-dev WEBSOCKETPP=OFF PEDANTIC=OFF NO_EXCEPTIONS=OFF BUILD_TYPE=Debug
 - GCC=g++-4.7 BOOST=libboost1.54-all-dev WEBSOCKETPP=OFF PEDANTIC=OFF NO_EXCEPTIONS=OFF BUILD_TYPE=Release
 - GCC=g++-4.6 BOOST=libboost1.55-all-dev WEBSOCKETPP=OFF PEDANTIC=OFF NO_EXCEPTIONS=OFF BUILD_TYPE=Debug
 - GCC=g++-4.6 BOOST=libboost1.54-all-dev WEBSOCKETPP=OFF PEDANTIC=OFF NO_EXCEPTIONS=OFF BUILD_TYPE=Release

before_install:
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo add-apt-repository -y ppa:boost-latest/ppa
 - sudo apt-get update -qq
 - sudo apt-get install -qq cmake liburiparser-dev $GCC $BOOST
 - git submodule update --init --recursive

script:
 - mkdir build
 - cd build
 - cmake .. -DSILICIUM_USE_WEBSOCKETPP=$WEBSOCKETPP -DSILICIUM_TEST_INCLUDES=ON -DSILICIUM_PEDANTIC=$PEDANTIC -DSILICIUM_NO_EXCEPTIONS=$NO_EXCEPTIONS -DCMAKE_BUILD_TYPE=$BUILD_TYPE
 - cmake --build . -- -j2
 - cd test
 - ./unit_test
