language: cpp
os:
 - linux
notifications:
 email:
  recipients:
   - tyroxxxx@gmail.com
  on_success: change # [always|never|change] # default: change
  on_failure: change # [always|never|change] # default: always

compiler:
 - clang
 - gcc
  
before_install:
 - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
 - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo add-apt-repository -y ppa:boost-latest/ppa; fi
 - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update -qq; fi
 - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install -qq libboost1.55-all-dev cmake; fi
 - if [ "$TRAVIS_OS_NAME" = "linux" ] && [ $GCCVER != "" ]; then sudo apt-get install -qq $GCCVER; fi
 - git submodule update --init --recursive

script:
 - mkdir build
 - cd build
 - cmake ..
 - cmake --build .
 - ./test/unit_test
