language: cpp
os:
 - linux
sudo: true
notifications:
 email:
  on_success: change # [always|never|change] # default: change
  on_failure: always # [always|never|change] # default: always

addons:
  apt:
    sources:
    - boost-latest
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
    - g++-4.9
    - g++-4.8
    - g++-4.7
    - libboost1.55-all-dev
    
env:
 - CPP=g++-5   WEBSOCKETPP=OFF PEDANTIC=ON  NO_EXCEPTIONS=ON  NO_RTTI=OFF TEST_INCLUDES=OFF WARNING_IS_ERROR=ON BUILD_TYPE=Release
 - CPP=g++-5   WEBSOCKETPP=OFF PEDANTIC=ON  NO_EXCEPTIONS=OFF NO_RTTI=ON  TEST_INCLUDES=OFF WARNING_IS_ERROR=ON BUILD_TYPE=Release
 - CPP=g++-5   WEBSOCKETPP=OFF PEDANTIC=ON  NO_EXCEPTIONS=OFF NO_RTTI=OFF TEST_INCLUDES=ON  WARNING_IS_ERROR=ON BUILD_TYPE=Release
 - CPP=g++-5   WEBSOCKETPP=OFF PEDANTIC=ON  NO_EXCEPTIONS=OFF NO_RTTI=OFF TEST_INCLUDES=OFF WARNING_IS_ERROR=ON BUILD_TYPE=Debug
 - CPP=g++-4.9 WEBSOCKETPP=OFF PEDANTIC=OFF NO_EXCEPTIONS=OFF NO_RTTI=OFF TEST_INCLUDES=OFF WARNING_IS_ERROR=ON BUILD_TYPE=Release
 - CPP=g++-4.9 WEBSOCKETPP=OFF PEDANTIC=OFF NO_EXCEPTIONS=OFF NO_RTTI=OFF TEST_INCLUDES=OFF WARNING_IS_ERROR=ON BUILD_TYPE=Debug
 - CPP=g++-4.8 WEBSOCKETPP=OFF PEDANTIC=OFF NO_EXCEPTIONS=OFF NO_RTTI=OFF TEST_INCLUDES=OFF WARNING_IS_ERROR=ON BUILD_TYPE=Release
 - CPP=g++-4.8 WEBSOCKETPP=OFF PEDANTIC=OFF NO_EXCEPTIONS=OFF NO_RTTI=OFF TEST_INCLUDES=OFF WARNING_IS_ERROR=ON BUILD_TYPE=Debug
 - CPP=g++-4.7 WEBSOCKETPP=OFF PEDANTIC=OFF NO_EXCEPTIONS=OFF NO_RTTI=OFF TEST_INCLUDES=OFF WARNING_IS_ERROR=ON BUILD_TYPE=Debug
 - CPP=g++-4.7 WEBSOCKETPP=OFF PEDANTIC=OFF NO_EXCEPTIONS=OFF NO_RTTI=OFF TEST_INCLUDES=OFF WARNING_IS_ERROR=ON BUILD_TYPE=Release
 - UPLOAD=YES

before_install:
 - git submodule update --init --recursive

script:
 - if [ $UPLOAD == "YES" ]; then
     wget https://s3-eu-west-1.amazonaws.com/conanio-production/downloads/conan-ubuntu-64_0_8_6.deb -O conan.deb || exit 1;
     sudo dpkg -i conan.deb || exit 1;
     rm conan.deb || exit 1;
     conan --version;
     wget https://s3.amazonaws.com/biibinaries/thirdparty/cmake-3.0.2-Linux-64.tar.gz;
     tar -xzf cmake-3.0.2-Linux-64.tar.gz;
     sudo cp -fR cmake-3.0.2-Linux-64/* /usr;
     rm -rf cmake-3.0.2-Linux-64;
     rm cmake-3.0.2-Linux-64.tar.gz;
     conan user TyRoXx -p $CONAN_PASSWORD || exit 1;
     conan export TyRoXx/master || exit 1;
     conan install silicium/0.11@TyRoXx/master --build=silicium || exit 1;
     conan upload --all silicium/0.11@TyRoXx/master || exit 1;
     exit 0;
   fi
 - mkdir build-silicium
 - pushd build-silicium
 - CXX=$CPP cmake .. -DSILICIUM_USE_WEBSOCKETPP=$WEBSOCKETPP -DSILICIUM_TEST_INCLUDES=$TEST_INCLUDES -DSILICIUM_PEDANTIC=$PEDANTIC -DSILICIUM_NO_EXCEPTIONS=$NO_EXCEPTIONS -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DSILICIUM_NO_RTTI=$NO_RTTI -DSILICIUM_WARNING_IS_ERROR=$WARNING_IS_ERROR || exit 1
 - cmake --build . -- -j2 || exit 1
 - pushd test
 - if [ $NO_RTTI != "ON" ]; then
     ./unit_test || exit 1;
   fi
